apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bikesharing-location
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
    retention.ms: -1
  partitions: 1
  replicas: 3
  topicName: BIKESHARING.LOCATION
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bikesharing-weather
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
    retention.ms: -1
  partitions: 1
  replicas: 3
  topicName: BIKESHARING.WEATHER
